"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-27 15:21:48.114549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("root_path", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "samples",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "canonical_name", name="uq_sample_canonical_name"),
    )
    with op.batch_alter_table("samples", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_samples_project_id"), ["project_id"], unique=False)

    op.create_table(
        "measurements",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("sample_id", sa.String(length=32), nullable=False),
        sa.Column("technique", sa.String(), nullable=False),
        sa.Column("instrument", sa.String(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column("parsed_data_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["sample_id"], ["samples.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_measurements_sample_id"), ["sample_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_measurements_technique"), ["technique"], unique=False)

    op.create_table(
        "files",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("measurement_id", sa.String(length=32), nullable=True),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["measurement_id"], ["measurements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_file_sha256"),
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_files_measurement_id"), ["measurement_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_files_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_files_sha256"), ["sha256"], unique=False)

    op.create_table(
        "validation_issues",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("measurement_id", sa.String(length=32), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["measurement_id"], ["measurements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("validation_issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_validation_issues_measurement_id"), ["measurement_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_validation_issues_severity"), ["severity"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("validation_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_validation_issues_severity"))
        batch_op.drop_index(batch_op.f("ix_validation_issues_measurement_id"))

    op.drop_table("validation_issues")
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_sha256"))
        batch_op.drop_index(batch_op.f("ix_files_project_id"))
        batch_op.drop_index(batch_op.f("ix_files_measurement_id"))

    op.drop_table("files")
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_measurements_technique"))
        batch_op.drop_index(batch_op.f("ix_measurements_sample_id"))

    op.drop_table("measurements")
    with op.batch_alter_table("samples", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_samples_project_id"))

    op.drop_table("samples")
    op.drop_table("projects")
    # ### end Alembic commands ###
